---
- name: Reload NetworkManager connection eth1
  ansible.builtin.shell: test {{ ansible_check_mode | lower }} = false && nmcli con up "cloud-init eth1"
  check_mode: false
  changed_when: not ansible_check_mode

- name: Restart corosync
  ansible.builtin.systemd_service:
    name: corosync
    state: restarted

- name: Restart pacemaker
  ansible.builtin.systemd_service:
    name: pacemaker
    state: restarted
