---
- name: Reload NetworkManager connection eth1
  ansible.builtin.command: nmcli con up "cloud-init eth1"
  changed_when: true

- name: Restart corosync
  ansible.builtin.systemd_service:
    name: corosync
    state: restarted

- name: Restart pacemaker
  ansible.builtin.systemd_service:
    name: pacemaker
    state: restarted
