---
- name: Fix eth1 DNS contamination
  ansible.builtin.import_tasks: fix-eth1-dns.yaml
- name: Setup Pacemaker
  ansible.builtin.import_tasks: pacemaker.yaml
- name: Setup Pacemaker QDevice
  ansible.builtin.import_tasks: pacemaker_qdevice.yaml
- name: Setup DRBD
  ansible.builtin.import_tasks: drbd.yaml
- name: Setup MariaDB
  ansible.builtin.import_tasks: mariadb.yaml
