---
- name: repos | Enable HighAvailability repository
  ansible.builtin.yum_repository:
    name: highavailability
    file: almalinux-highavailability
    description: AlmaLinux $releasever - HighAvailability
    mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/highavailability
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-{{ ansible_facts['distribution_major_version'] }}
    enabled: true
    module_hotfixes: true

- name: pacemaker_qdevice | Install Pacemaker QDevice
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.package:
    name:
      - corosync-qnetd
      - pcs
    state: present

- name: pacemaker_qdevice | Set hacluster user password
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.user:
    name: hacluster
    password: "{{ zabbix_server_hacluster_password | password_hash('sha512') }}"
  changed_when: false

- name: pacemaker_qdevice | Check if qnetd NSS cert DB is initialized
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.stat:
    path: /etc/corosync/qnetd/nssdb/cert9.db
  register: qnetd_certdb

- name: pacemaker_qdevice | Initialize qnetd NSS certificate database
  when:
    - inventory_hostname in groups['zabbix_server__qdevice']
    - not qnetd_certdb.stat.exists
  block:
    - name: pacemaker_qdevice | Remove stale NSS cert database
      ansible.builtin.file:
        path: /etc/corosync/qnetd/nssdb
        state: absent

    - name: pacemaker_qdevice | Run certutil init
      ansible.builtin.command:
        cmd: corosync-qnetd-certutil -i
        creates: /etc/corosync/qnetd/nssdb

- name: pacemaker_qdevice | Enable and start pcsd
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.systemd_service:
    name: pcsd
    state: started
    enabled: true

- name: pacemaker_qdevice | Enable and start corosync-qnetd
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.systemd_service:
    name: corosync-qnetd
    state: started
    enabled: true
