---
- name: repos | Enable HighAvailability repository
  ansible.builtin.yum_repository:
    name: highavailability
    file: almalinux-highavailability
    description: AlmaLinux $releasever - HighAvailability
    mirrorlist: https://mirrors.almalinux.org/mirrorlist/$releasever/highavailability
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux-{{ ansible_facts['distribution_major_version'] }}
    enabled: true
    module_hotfixes: true

- name: pacemaker_qdevice | Install Pacemaker QDevice
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.package:
    name:
      - corosync-qnetd
      - pcs
    state: present

- name: pacemaker_qdevice | Set hacluster user password
  when: "inventory_hostname in groups['zabbix_server__qdevice']"
  ansible.builtin.user:
    name: hacluster
    password: "{{ zabbix_server_hacluster_password | password_hash('sha512') }}"
  changed_when: false
