---
### ELRepo ###

- name: Import ELRepo repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://www.elrepo.org/RPM-GPG-KEY-v2-elrepo.org
    state: present

- name: Install ELRepo
  become: true
  ansible.builtin.dnf:
    name: https://www.elrepo.org/elrepo-release-10.el10.elrepo.noarch.rpm
    state: present

### MariaDB ###

- name: Copy MariaDB repo
  become: true
  ansible.builtin.copy:
    src: files/MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
    mode: "0644"

### Zabbix ###

- name: Import Zabbix repo key
  become: true
  ansible.builtin.rpm_key:
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
    state: present

- name: Install Zabbix repo
  become: true
  ansible.builtin.dnf:
    name: https://repo.zabbix.com/zabbix/7.0/alma/10/x86_64/zabbix-release-latest-7.0.el10.noarch.rpm
    state: present
    disable_gpg_check: true
