---
- name: Check DNS forwarding changes
  ansible.builtin.set_fact:
    _dns_changed: >-
      {{ (lookup('ansible.builtin.template', role_path + '/templates/dns.j2')
          .splitlines() | select('match', '^set ') | map('regex_replace', "[\r'\"]", '') | list | sort)
         !=
         (_all_config.stdout_lines[0] | select('match', '^set service dns') | map('regex_replace', "[\r'\"]", '') | list | sort) }}

- name: Deploy DNS forwarding script
  ansible.builtin.template:
    src: dns.j2
    dest: /tmp/vyos-dns.sh
    mode: "0700"
  changed_when: false
  when: _dns_changed
  vars:
    ansible_connection: ssh

- name: Execute DNS forwarding script
  ansible.builtin.shell: /tmp/vyos-dns.sh
  when: _dns_changed
  vars:
    ansible_connection: ssh

- name: Remove DNS forwarding script
  ansible.builtin.file:
    path: /tmp/vyos-dns.sh
    state: absent
  changed_when: false
  when: _dns_changed
  vars:
    ansible_connection: ssh
