[tasks.show-inventory]
run = "uv run ansible-inventory -i inventory_src.yaml --list --yaml"

[tasks.play-ansible]
run = "uv run ansible-playbook ${usage_playbook:?} -i inventory_src.yaml"
usage = '''
arg "<playbook>" help="Which playbook do you want to play?"
'''

[tasks.ping]
run = "uv run ansible -i inventory_src.yaml -m ping all"
