---
fw_domain_groups:
  - name: ALMALINUX_MIRRORS
    domains:
      - mirrors.almalinux.org
      - repo.almalinux.org
      - ftp.udx.icscoe.jp
      - ftp.iij.ad.jp
      - ftp.jaist.ac.jp
      - ftp.sakura.ad.jp
      - ftp.riken.jp
      - ftp.yz.yamagata-u.ac.jp
      - mirrors.xtom.jp
      - alma.acidman.thelefty.org
  - name: ELREPO_MIRRORS
    domains:
      - www.elrepo.org
      - elrepo.org
      - mirrors.elrepo.org
      - mirrors.coreix.net
      - mirror.rackspace.com
      - linux-mirrors.fnal.gov
  - name: COPR
    domains:
      - copr.fedorainfracloud.org
      - download.copr.fedorainfracloud.org
  - name: ADGUARD
    domains:
      - static.adtidy.org
      - adguardteam.github.io
  - name: GITHUB
    domains:
      - github.com
      - objects.githubusercontent.com
  - name: LETSENCRYPT
    domains:
      - acme-v02.api.letsencrypt.org
  - name: CLOUDFLARE_API
    domains:
      - api.cloudflare.com
  - name: EASYLIST
    domains:
      - easylist.to
  - name: DEBIAN_MIRRORS
    domains:
      - deb.debian.org
      - security.debian.org

fw_network_groups:
  - name: HOME_CLIENTS
    networks:
      - 192.168.10.0/24
  - name: CLOUDFLARE_IPS
    networks:
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22

fw_address_groups:
  - name: WAN_GATEWAY
    addresses:
      - 192.168.20.1
  - name: PVE_NODES
    addresses:
      - 192.168.20.2
  - name: FW_WAN_VIP
    addresses:
      - 192.168.20.3
  - name: FW_WAN_NODES
    addresses:
      - 192.168.20.4
      - 192.168.20.5
  - name: TAILSCALE_NODES
    addresses:
      - 192.168.20.20
      - 192.168.20.21
  - name: FW_DMZ_VIP
    addresses:
      - 192.168.20.17
  - name: FW_DMZ_NODES
    addresses:
      - 192.168.20.18
      - 192.168.20.19
  - name: DNS_SERVERS
    addresses:
      - 192.168.20.22
      - 192.168.20.23
  - name: ACCESS_SWITCHES
    addresses:
      - 192.168.22.1
  - name: FW_INTERNAL_VIP
    addresses:
      - 192.168.22.3
  - name: NAS_SERVERS
    addresses:
      - 192.168.22.6
  - name: ZABBIX_SERVERS
    addresses:
      - 192.168.22.8
      - 192.168.22.9
  - name: VRRP_MULTICAST
    addresses:
      - 224.0.0.18
