---
- name: Setup Pacemaker
  ansible.builtin.import_tasks: pacemaker.yaml
- name: Setup DRBD
  ansible.builtin.import_tasks: drbd.yaml
- name: Setup MariaDB
  ansible.builtin.import_tasks: mariadb.yaml
