---
- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded

- name: Restart AdGuardHome
  when: "'dns_server' in group_names"
  ansible.builtin.systemd_service:
    name: AdGuardHome
    state: restarted
