---
- name: Get full configuration commands
  vyos.vyos.vyos_command:
    commands:
      - show configuration commands
  register: vyos_all_config

- name: Configure system settings
  ansible.builtin.import_tasks: system.yaml
- name: Configure DNS forwarding
  ansible.builtin.import_tasks: dns.yaml
- name: Configure firewall
  ansible.builtin.import_tasks: firewall.yaml
- name: Configure VRRP
  ansible.builtin.import_tasks: vrrp.yaml

- name: Compare running vs saved configuration
  ansible.builtin.shell: |
    source /opt/vyatta/etc/functions/script-template
    configure
    compare saved
    exit
  args:
    executable: /bin/vbash
  changed_when: false
  register: vyos_compare_saved
  vars:
    ansible_connection: ssh

- name: Display changes since last save
  ansible.builtin.debug:
    msg: "{{ vyos_compare_saved.stdout_lines }}"
  when: "'No changes' not in vyos_compare_saved.stdout"

- name: Save configuration
  vyos.vyos.vyos_config:
    save: true
