---
- name: Configure basic settings
  vyos.vyos.vyos_config:
    lines:
      - set system host-name {{ inventory_hostname }}
      - set system time-zone Asia/Tokyo
      - set system config-management commit-revisions 20
      - set system login max-login-session 5
      - set system login timeout 600
      - set system ipv6
      - set system sysctl parameter net.ipv4.tcp_syncookies value '1'
      - set interfaces ethernet eth0 description 'Upstream'
      - set interfaces ethernet eth1 address {{ vyos_eth1_address }}
      - set interfaces ethernet eth1 description 'DMZ'
      - set interfaces ethernet eth2 address {{ vyos_eth2_address }}
      - set interfaces ethernet eth2 description 'Service'
      - set interfaces ethernet eth3 address {{ vyos_eth3_address }}
      - set interfaces ethernet eth3 description 'Internal'
      - set service ssh disable-password-authentication
      - set system name-server {{ vyos_dns_server }}
    save: false

- name: Check NTP changes
  ansible.builtin.set_fact:
    vyos_ntp_changed: >-
      {{ (lookup('ansible.builtin.template', role_path + '/templates/ntp.j2')
          .splitlines() | select('match', '^set ') | map('regex_replace', "[\r'\"]", '') | list | sort)
         !=
         (vyos_all_config.stdout_lines[0] | select('match', '^set service ntp') | map('regex_replace', "[\r'\"]", '') | list | sort) }}

- name: Deploy NTP script
  ansible.builtin.template:
    src: ntp.j2
    dest: /tmp/vyos-ntp.sh
    mode: "0700"
  changed_when: false
  when: vyos_ntp_changed
  vars:
    ansible_connection: ssh

- name: Execute NTP script
  ansible.builtin.command: /tmp/vyos-ntp.sh
  when: vyos_ntp_changed
  changed_when: true
  vars:
    ansible_connection: ssh

- name: Remove NTP script
  ansible.builtin.file:
    path: /tmp/vyos-ntp.sh
    state: absent
  changed_when: false
  when: vyos_ntp_changed
  vars:
    ansible_connection: ssh

- name: Remove default operator-group
  vyos.vyos.vyos_config:
    lines:
      - delete system login operator-group default
    save: false
