[env]
KRB5_CONFIG = "./ansible/files/krb5.conf"
KRB5_CLIENT_KTNAME = "./ansible/files/machine-user.keytab"

[tasks.show-inventory]
run = "uv run ansible-inventory -i ansible/inventory_src.yaml --list --yaml"

[tasks.play-ansible]
run = "uv run ansible-playbook ${usage_playbook:?} -i ansible/inventory_src.yaml"
usage = '''
arg "<playbook>" help="Which playbook do you want to play?"
'''
