---
- name: Remove local DNF mirror configuration (not applicable on this host)
  when:
    - ansible_facts['distribution'] == 'AlmaLinux'
    - dnf_local_mirror_urls | default([]) | length == 0
  block:
    - name: Remove local mirror repo file
      become: true
      ansible.builtin.file:
        path: /etc/yum.repos.d/local-mirror.repo
        state: absent

    - name: Re-enable default AlmaLinux repositories
      become: true
      community.general.ini_file:
        path: "/etc/yum.repos.d/almalinux-{{ item }}.repo"
        section: "{{ item }}"
        option: enabled
        value: "1"
        mode: "0644"
      loop:
        - baseos
        - appstream
        - crb
        - extras

- name: Configure local DNF mirror
  when:
    - ansible_facts['distribution'] == 'AlmaLinux'
    - dnf_local_mirror_urls | default([]) | length > 0
  block:
    - name: Deploy local mirror repo file
      become: true
      ansible.builtin.template:
        src: local-mirror.repo.j2
        dest: /etc/yum.repos.d/local-mirror.repo
        owner: root
        group: root
        mode: "0644"

    - name: Disable default AlmaLinux repositories
      become: true
      community.general.ini_file:
        path: "/etc/yum.repos.d/almalinux-{{ item }}.repo"
        section: "{{ item }}"
        option: enabled
        value: "0"
        mode: "0644"
      loop:
        - baseos
        - appstream
        - crb
        - extras
