---
- name: Configure sudoers to keep SSH_AUTH_SOCK
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ssh-auth-sock
    content: 'Defaults env_keep += "SSH_AUTH_SOCK"'
    owner: root
    group: root
    mode: '0440'
    validate: visudo -cf %s

- name: Configure PAM sudo to use SSH agent auth
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pam.d/sudo
    insertbefore: ^@include common-auth
    block: "auth sufficient pam_ssh_agent_auth.so file=~/.ssh/authorized_keys\n"
    marker: "# {mark} pam_ssh_agent_auth"
