#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        ct state established,related accept
        iif lo accept

        # Tailscale
        iifname "tailscale0" accept

        # SSH
        tcp dport ssh accept

        # ICMP
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # UDP traceroute (Linux traceroute default ports)
        udp dport 33434-33534 accept
    }

    chain forward {
        # Tailscaleのサブネットルーティングのため転送を許可
        type filter hook forward priority filter; policy accept;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
