---
vyos_vrrp_preempt_delay: 20
vyos_vrrp_track_interface: eth0
vyos_vrrp_sync_group: SYNC

vyos_vrrp_groups:
  - name: WAN
    vrid: 19
    interface: eth0
    address: 192.168.20.3/29
  - name: DMZ
    vrid: 20
    interface: eth1
    address: 192.168.20.17/28
  - name: Service
    vrid: 21
    interface: eth2
    address: 192.168.21.3/24
  - name: Internal
    vrid: 22
    interface: eth3
    address: 192.168.22.3/24
