---
- name: Configure DNS
  ansible.builtin.import_tasks: dns.yaml
- name: Configure DNF local mirror
  ansible.builtin.import_tasks: dnf-local-mirror.yaml
- name: Install packages
  ansible.builtin.import_tasks: packages.yaml
- name: Setup package upgrade
  ansible.builtin.import_tasks: pkg-upgrade.yaml
- name: Configure timezone
  ansible.builtin.import_tasks: timezone.yaml
- name: Configure passwordless sudo
  ansible.builtin.import_tasks: passwordless-sudo.yaml
- name: Configure IP forwarding
  ansible.builtin.import_tasks: ip-forwarding.yaml
- name: Disable swap
  ansible.builtin.import_tasks: disable-swap.yaml
- name: Configure nftables
  ansible.builtin.import_tasks: use-nftables.yaml
- name: Install QEMU guest agent
  ansible.builtin.import_tasks: qemu-guest-agent.yaml
- name: Configure NTP
  ansible.builtin.import_tasks: ntp.yaml
