---
- name: Configure DNS and Proxy servers
  hosts: dns_server, proxy_server
  become: true
  gather_facts: true
  tags: [dns-proxy, dns, proxy, certificate]
  roles:
    - role: common
      tags: [common]
    - role: lego
      tags: [lego, certificate]
    - role: adguard
      tags: [adguard, dns]
    - role: squid
      tags: [squid, proxy]
