---
- name: Configure DNS servers
  hosts: dns_server
  gather_facts: true
  roles:
    - common
    - lego
    - adguard

- name: Configure Proxy servers
  hosts: proxy_server
  gather_facts: true
  roles:
    - squid
