---
- name: Configure Tailscale servers
  hosts: tailscale_server
  become: true
  gather_facts: true
  tags: [tailscale-server, tailscale]
  roles:
    - role: common
      tags: [common]
    - role: tailscale
      tags: [tailscale, vpn]
