---
- name: hardening | Remove cloud-init sudoers file
  ansible.builtin.file:
    path: /etc/sudoers.d/90-cloud-init-users
    state: absent

- name: hardening | Install libpam-ssh-agent-auth
  ansible.builtin.apt:
    name: libpam-ssh-agent-auth
    state: present
    install_recommends: false
