---
- name: Download Tailscale install script
  become: true
  ansible.builtin.get_url:
    url: https://tailscale.com/install.sh
    dest: /tmp/tailscale-install.sh
    mode: "0700"

- name: Install Tailscale
  become: true
  ansible.builtin.command: /tmp/tailscale-install.sh
  args:
    creates: /usr/bin/tailscale
