---
- name: keepalived | Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: keepalived | Deploy keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0600"
  notify: Restart keepalived

- name: keepalived | Enable and start keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    state: started
    enabled: true
