---
- name: Configure dnsmasq
  ansible.builtin.import_tasks: dnsmasq.yaml

- name: Configure nftables
  ansible.builtin.import_tasks: nftables.yaml

- name: Configure keepalived
  ansible.builtin.import_tasks: keepalived.yaml
