---
- name: Check if Administrator has SmartcardLogonRequired enabled
  ansible.windows.win_powershell:
    script: |
      $user = Get-ADUser -Identity "Administrator" -Properties SmartcardLogonRequired
      if (-not $user.SmartcardLogonRequired) { throw "SmartcardLogonRequired is not enabled" }
  register: admin_smartcard_check
  check_mode: false
  failed_when: false
  changed_when: false

- name: Enable SmartcardLogonRequired for Administrator
  when: admin_smartcard_check.error | length != 0
  ansible.windows.win_powershell:
    script: Set-ADUser -Identity "Administrator" -SmartcardLogonRequired $true
  check_mode: false
  register: admin_smartcard
  failed_when: ansible_check_mode == false and admin_smartcard.error | length != 0

- name: Check if Administrator has AccountNotDelegated enabled
  ansible.windows.win_powershell:
    script: |
      $user = Get-ADUser -Identity "Administrator" -Properties AccountNotDelegated
      if (-not $user.AccountNotDelegated) { throw "AccountNotDelegated is not enabled" }
  register: admin_not_delegated_check
  check_mode: false
  failed_when: false
  changed_when: false

- name: Enable AccountNotDelegated for Administrator
  when: admin_not_delegated_check.error | length != 0
  ansible.windows.win_powershell:
    script: Set-ADAccountControl -Identity "Administrator" -AccountNotDelegated $true
  check_mode: false
  register: admin_not_delegated
  failed_when: ansible_check_mode == false and admin_not_delegated.error | length != 0
