name: Lint Ansible
on:
  pull_request:
    branches:
      - main
jobs:
  find_envs:
    name: Find environments
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.output_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: output_matrix
        run: |
          echo "matrix=$(find ./ansible -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | jq -R -s -c 'split("\n") | map(select(length > 0)) | {env: .}')" >> $GITHUB_OUTPUT
  lint:
    name: Lint Ansible files
    runs-on: ubuntu-24.04
    needs: [ find_envs ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.find_envs.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.4.0
        with:
          working_directory: ${{ github.workspace }}/ansible/${{ matrix.env }}
