name: Lint Markdown
on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  pull_request:
jobs:
  lint:
    name: Lint Markdown
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - name: Lint markdown files
      uses: DavidAnson/markdownlint-cli2-action@v20
      with:
        globs: '**/*.md'
        config: .github/.markdownlint.yaml
